// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/infer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PredictRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional model identifier; empty for default.
	Model string `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	// Input payload, serialized as JSON string. Keep flexible to match existing Python API.
	InputJson     string `protobuf:"bytes,2,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_proto_infer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_infer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_proto_infer_proto_rawDescGZIP(), []int{0}
}

func (x *PredictRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *PredictRequest) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

type PredictResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Result serialized as JSON string. If error is set, result_json may be empty.
	ResultJson    string `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictResponse) Reset() {
	*x = PredictResponse{}
	mi := &file_proto_infer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictResponse) ProtoMessage() {}

func (x *PredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_infer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictResponse.ProtoReflect.Descriptor instead.
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return file_proto_infer_proto_rawDescGZIP(), []int{1}
}

func (x *PredictResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *PredictResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BatchPredictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*PredictRequest      `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPredictRequest) Reset() {
	*x = BatchPredictRequest{}
	mi := &file_proto_infer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPredictRequest) ProtoMessage() {}

func (x *BatchPredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_infer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPredictRequest.ProtoReflect.Descriptor instead.
func (*BatchPredictRequest) Descriptor() ([]byte, []int) {
	return file_proto_infer_proto_rawDescGZIP(), []int{2}
}

func (x *BatchPredictRequest) GetRequests() []*PredictRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type BatchPredictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*PredictResponse     `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPredictResponse) Reset() {
	*x = BatchPredictResponse{}
	mi := &file_proto_infer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPredictResponse) ProtoMessage() {}

func (x *BatchPredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_infer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPredictResponse.ProtoReflect.Descriptor instead.
func (*BatchPredictResponse) Descriptor() ([]byte, []int) {
	return file_proto_infer_proto_rawDescGZIP(), []int{3}
}

func (x *BatchPredictResponse) GetResponses() []*PredictResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_infer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_infer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_infer_proto_rawDescGZIP(), []int{4}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // e.g. "ok", "starting", "error"
	Details       string                 `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_infer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_infer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_infer_proto_rawDescGZIP(), []int{5}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

var File_proto_infer_proto protoreflect.FileDescriptor

const file_proto_infer_proto_rawDesc = "" +
	"\n" +
	"\x11proto/infer.proto\x12\x0efailsafe.infer\"E\n" +
	"\x0ePredictRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"input_json\x18\x02 \x01(\tR\tinputJson\"H\n" +
	"\x0fPredictResponse\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\tR\n" +
	"resultJson\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"Q\n" +
	"\x13BatchPredictRequest\x12:\n" +
	"\brequests\x18\x01 \x03(\v2\x1e.failsafe.infer.PredictRequestR\brequests\"U\n" +
	"\x14BatchPredictResponse\x12=\n" +
	"\tresponses\x18\x01 \x03(\v2\x1f.failsafe.infer.PredictResponseR\tresponses\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\adetails\x18\x02 \x01(\tR\adetails2\x81\x02\n" +
	"\tInference\x12L\n" +
	"\aPredict\x12\x1e.failsafe.infer.PredictRequest\x1a\x1f.failsafe.infer.PredictResponse\"\x00\x12[\n" +
	"\fBatchPredict\x12#.failsafe.infer.BatchPredictRequest\x1a$.failsafe.infer.BatchPredictResponse\"\x00\x12I\n" +
	"\x06Health\x12\x1d.failsafe.infer.HealthRequest\x1a\x1e.failsafe.infer.HealthResponse\"\x00B7Z5github.com/dhruvjaink07/failsafe/internal/proto;protob\x06proto3"

var (
	file_proto_infer_proto_rawDescOnce sync.Once
	file_proto_infer_proto_rawDescData []byte
)

func file_proto_infer_proto_rawDescGZIP() []byte {
	file_proto_infer_proto_rawDescOnce.Do(func() {
		file_proto_infer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_infer_proto_rawDesc), len(file_proto_infer_proto_rawDesc)))
	})
	return file_proto_infer_proto_rawDescData
}

var file_proto_infer_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_infer_proto_goTypes = []any{
	(*PredictRequest)(nil),       // 0: failsafe.infer.PredictRequest
	(*PredictResponse)(nil),      // 1: failsafe.infer.PredictResponse
	(*BatchPredictRequest)(nil),  // 2: failsafe.infer.BatchPredictRequest
	(*BatchPredictResponse)(nil), // 3: failsafe.infer.BatchPredictResponse
	(*HealthRequest)(nil),        // 4: failsafe.infer.HealthRequest
	(*HealthResponse)(nil),       // 5: failsafe.infer.HealthResponse
}
var file_proto_infer_proto_depIdxs = []int32{
	0, // 0: failsafe.infer.BatchPredictRequest.requests:type_name -> failsafe.infer.PredictRequest
	1, // 1: failsafe.infer.BatchPredictResponse.responses:type_name -> failsafe.infer.PredictResponse
	0, // 2: failsafe.infer.Inference.Predict:input_type -> failsafe.infer.PredictRequest
	2, // 3: failsafe.infer.Inference.BatchPredict:input_type -> failsafe.infer.BatchPredictRequest
	4, // 4: failsafe.infer.Inference.Health:input_type -> failsafe.infer.HealthRequest
	1, // 5: failsafe.infer.Inference.Predict:output_type -> failsafe.infer.PredictResponse
	3, // 6: failsafe.infer.Inference.BatchPredict:output_type -> failsafe.infer.BatchPredictResponse
	5, // 7: failsafe.infer.Inference.Health:output_type -> failsafe.infer.HealthResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_infer_proto_init() }
func file_proto_infer_proto_init() {
	if File_proto_infer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_infer_proto_rawDesc), len(file_proto_infer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_infer_proto_goTypes,
		DependencyIndexes: file_proto_infer_proto_depIdxs,
		MessageInfos:      file_proto_infer_proto_msgTypes,
	}.Build()
	File_proto_infer_proto = out.File
	file_proto_infer_proto_goTypes = nil
	file_proto_infer_proto_depIdxs = nil
}
