# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/infer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/infer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/infer.proto\x12\x0e\x66\x61ilsafe.infer\"3\n\x0ePredictRequest\x12\r\n\x05model\x18\x01 \x01(\t\x12\x12\n\ninput_json\x18\x02 \x01(\t\"5\n\x0fPredictResponse\x12\x13\n\x0bresult_json\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"G\n\x13\x42\x61tchPredictRequest\x12\x30\n\x08requests\x18\x01 \x03(\x0b\x32\x1e.failsafe.infer.PredictRequest\"J\n\x14\x42\x61tchPredictResponse\x12\x32\n\tresponses\x18\x01 \x03(\x0b\x32\x1f.failsafe.infer.PredictResponse\"\x0f\n\rHealthRequest\"1\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x02 \x01(\t2\x81\x02\n\tInference\x12L\n\x07Predict\x12\x1e.failsafe.infer.PredictRequest\x1a\x1f.failsafe.infer.PredictResponse\"\x00\x12[\n\x0c\x42\x61tchPredict\x12#.failsafe.infer.BatchPredictRequest\x1a$.failsafe.infer.BatchPredictResponse\"\x00\x12I\n\x06Health\x12\x1d.failsafe.infer.HealthRequest\x1a\x1e.failsafe.infer.HealthResponse\"\x00\x42\x37Z5github.com/dhruvjaink07/failsafe/internal/proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.infer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/dhruvjaink07/failsafe/internal/proto;proto'
  _globals['_PREDICTREQUEST']._serialized_start=37
  _globals['_PREDICTREQUEST']._serialized_end=88
  _globals['_PREDICTRESPONSE']._serialized_start=90
  _globals['_PREDICTRESPONSE']._serialized_end=143
  _globals['_BATCHPREDICTREQUEST']._serialized_start=145
  _globals['_BATCHPREDICTREQUEST']._serialized_end=216
  _globals['_BATCHPREDICTRESPONSE']._serialized_start=218
  _globals['_BATCHPREDICTRESPONSE']._serialized_end=292
  _globals['_HEALTHREQUEST']._serialized_start=294
  _globals['_HEALTHREQUEST']._serialized_end=309
  _globals['_HEALTHRESPONSE']._serialized_start=311
  _globals['_HEALTHRESPONSE']._serialized_end=360
  _globals['_INFERENCE']._serialized_start=363
  _globals['_INFERENCE']._serialized_end=620
# @@protoc_insertion_point(module_scope)
